### ISSUE TITLE
&nbsp; results in snapshots passed!

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [horvay/jasmine-snapshot#3]
If I have a div that contains &nbsp;, the match always succeeds!

<div style="margin-left: 0px;"><span><div class="blah style="background-color: rgb(0, 0, 255); color: rgb(255, 255, 0);">&nbsp;</div></span>

When I remove the &nbsp; it works as expected.

strange!

**Comment by horvay** [comment]
Interestingly enough, if there is a `&nbsp;` in an HTML tag in a non-standard location, it fails to convert the html into json, and throws an exception. (Jasmine doesn't catch exceptions though unless you tell it to.)

So `<div id="aoeu&nbsp;"></div>` is fine and will turn your html into JSON to be snapshotted. 

However, `<div id="aoeu" &nbsp;></div>` will break it and do unpredictable things since `&nbsp;` is not a valid html attribute.



Do you have a real case where you need to have the `&nbsp;` be in your html tag?

**Comment by horvay** [comment]
Also, thank you for trying Jasmine Snapshot! I'll try to get back to you sooner in the future!

**Comment by Michael-Tajmajer-Emrsn** [comment]
Thanks for looking into this!  I fixed my generated code and all is well :-)
